base_model: /data/huggingface/gemma-3-4b-it

load_in_4bit: true

# gemma3 doesn't seem to play nice with ddp
ddp_find_unused_parameters: true

chat_template: gemma3
eot_tokens:
  - <end_of_turn>
datasets:
  - path: /data/meta-extractor/conversations/conversations_train_all_longer_text_english_metadata_prompt_ver4.jsonl #UPDATE PATH
    type: chat_template
    train_on_inputs: false
    field_messages: conversations
    message_property_mappings:
      role: role
      content: content


dataset_prepared_path: last_run_prepared
val_set_size: 0.01

output_dir: /data/meta-extractor/models/all_longer_text_english_metadata_prompt_ver4 #UPDATE PATH

adapter: qlora
lora_model_dir:

sequence_len: 4096
sample_packing: false


lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules: 'model.language_model.layers.[\d]+.(mlp|cross_attn|self_attn).(up|down|gate|q|k|v|o)_proj'

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 1
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

bf16: true
fp16:
tf32: true

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
logging_steps: 1
flash_attention: false
eager_attention:

warmup_ratio: 0.1
evals_per_epoch: 1
saves_per_epoch: 1
weight_decay: 0.0

# save_first_step: true  # uncomment this to validate checkpoint saving works with your config
